
/**************************************************************
 *	
 *	chaos, 8 bit, 11025Hz,
 *	1 channel, 363744 bytes/channel
 *	Total Size: 1 * 363744 + 4 (header) = 363788 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\CS2261\final-project-trexychan\sounds\chaos.wav
 *	Time-stamp: Mon Apr 20 15:25:14 2020
 *	
 **************************************************************/

#ifndef __CHAOSH__
#define __CHAOSH__

#define CHAOSFREQ 11025
#define CHAOSLEN 363744

extern const unsigned char chaos[363744];

#endif /* __CHAOSH__ */
