
/**************************************************************
 *	
 *	gunShot, 8 bit, 11025Hz,
 *	1 channel, 11008 bytes/channel
 *	Total Size: 1 * 11008 + 4 (header) = 11052 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\CS2261\final-project-trexychan\sounds\gunShot.wav
 *	Time-stamp: Mon Apr 20 09:29:33 2020
 *	
 **************************************************************/

#ifndef __GUNSHOTH__
#define __GUNSHOTH__

#define GUNSHOTFREQ 11025
#define GUNSHOTLEN 11008

extern const unsigned char gunShot[11008];

#endif /* __GUNSHOTH__ */
