
/**************************************************************
 *	
 *	panic, 8 bit, 11025Hz,
 *	1 channel, 693229 bytes/channel
 *	Total Size: 1 * 693229 + 4 (header) = 693273 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\CS2261\final-project-trexychan\sounds\panic.wav
 *	Time-stamp: Mon Apr 20 15:25:03 2020
 *	
 **************************************************************/

#ifndef __PANICH__
#define __PANICH__

#define PANICFREQ 11025
#define PANICLEN 693229

extern const unsigned char panic[693229];

#endif /* __PANICH__ */
